version: 2.1
jobs:
  build:
    docker:
      - image: currusci/flutter
    steps:
      - checkout
      - run: flutter clean 
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: 
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk


